version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"

  db:
    image: postgres:16.6-alpine3.19
    container_name: shortener-db
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    container_name: shortener-db-migrator
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure

volumes:
  postgres_data: