// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	url "github.com/kingxl111/url-shortener/internal/url"
)

// URLRepository is an autogenerated mock type for the URLRepository type
type URLRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *URLRepository) Create(ctx context.Context, _a1 url.URL) (*url.URL, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, url.URL) (*url.URL, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, url.URL) *url.URL); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, url.URL) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, shortenedUrl
func (_m *URLRepository) Get(ctx context.Context, shortenedUrl url.URL) (*url.URL, error) {
	ret := _m.Called(ctx, shortenedUrl)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, url.URL) (*url.URL, error)); ok {
		return rf(ctx, shortenedUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, url.URL) *url.URL); ok {
		r0 = rf(ctx, shortenedUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, url.URL) error); ok {
		r1 = rf(ctx, shortenedUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLRepository creates a new instance of URLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepository {
	mock := &URLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
